export function FormatTextVN(str: string) {
  str = str?.replace(/[àáạảãâầấậẩẫăằắặẳẵ]/g, 'a')
  str = str?.replace(/[èéẹẻẽêềếệểễ]/g, 'e')
  str = str?.replace(/[ìíịỉĩ]/g, 'i')
  str = str?.replace(/[òóọỏõôồốộổỗơờớợởỡ]/g, 'o')
  str = str?.replace(/[ùúụủũưừứựửữ]/g, 'u')
  str = str?.replace(/[ỳýỵỷỹ]/g, 'y')
  str = str?.replace(/đ/g, 'd')
  str = str?.replace(/[ÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴ]/g, 'A')
  str = str?.replace(/[ÈÉẸẺẼÊỀẾỆỂỄ]/g, 'E')
  str = str?.replace(/[ÌÍỊỈĨ]/g, 'I')
  str = str?.replace(/[ÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠ]/g, 'O')
  str = str?.replace(/[ÙÚỤỦŨƯỪỨỰỬỮ]/g, 'U')
  str = str?.replace(/[ỲÝỴỶỸ]/g, 'Y')
  str = str?.replace(/Đ/g, 'D')
  str = str?.replace(/[\u0300\u0301\u0303\u0309\u0323]/g, '')
  str = str?.replace(/\u02C6\u0306/g, '')
  str = str?.replace(/\u031B/g, '')
  str = str?.replace(/ + /g, ' ')
  str = str?.trim()
  str = str?.replace(/[!@%^*()+=<>?/,.:;'"&[]~$_`-{}|\\]/g, ' ')
  return str
}
